apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  namespace: portfolio
  name: letsencrypt-traefik-prod
spec:
  acme:
    email: s.theoulle@outlook.fr
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-traefik-prod
    solvers:
    - http01:
        ingress:
          class: traefik
