apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-srh
  labels:
    app: portfolio-srh
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-srh
  template:
    metadata:
      labels:
        app: portfolio-srh
    spec:
      containers:
      - name: portfolio-srh
        image: sarahth/portfolio-srh:latest
        ports:
        - containerPort: 80

