apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-srh-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        backend:
          service:
            name: portfolio-srh-service
            port:
              number: 80
