apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-srh-ingress
  namespace: portfolio
spec:
  rules:
    - http:
        paths:
          - path: /                # This is an absolute path
            pathType: Prefix
            backend:
              service:
                name: frontend-app
                port:
                  number: 80
